#!/usr/bin/env bash
# Bind dummy IP + persistent DNAT to OpenVPN UDP/TCP and WireGuard.
# Reads /etc/popout-vpn/dnat.env (generated by the installer / panel).
# shellcheck shell=bash
set -euo pipefail

ENV_FILE="${POPOUT_DNAT_ENV:-/etc/popout-vpn/dnat.env}"
if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a
fi

BIND_IP="${BIND_IP:-10.255.255.1}"
BIND_IFACE="${BIND_IFACE:-popout-bind}"
OVPN_UDP_ENABLED="${OVPN_UDP_ENABLED:-1}"
OVPN_TCP_ENABLED="${OVPN_TCP_ENABLED:-1}"
WG_ENABLED="${WG_ENABLED:-1}"
OVPN_UDP_PORT="${OVPN_UDP_PORT:-1194}"
OVPN_TCP_PORT="${OVPN_TCP_PORT:-1195}"
WG_PORT="${WG_PORT:-51820}"
EPHEMERAL_SET="${EPHEMERAL_SET:-ephemeral-ports}"
EPHEMERAL_PORT_MIN="${EPHEMERAL_PORT_MIN:-45000}"
EPHEMERAL_PORT_MAX="${EPHEMERAL_PORT_MAX:-45099}"
CHAIN="POPOUT_DNAT"
FILTER_CHAIN="POPOUT_INPUT"

ensure_bind_iface() {
  if ! ip link show "$BIND_IFACE" >/dev/null 2>&1; then
    if ! ip link add "$BIND_IFACE" type dummy 2>/dev/null; then
      BIND_IFACE="lo"
      if ! ip -4 addr show dev lo | grep -q " ${BIND_IP}/"; then
        ip addr add "${BIND_IP}/32" dev lo
      fi
      return
    fi
  fi
  ip link set "$BIND_IFACE" up
  if ! ip -4 addr show dev "$BIND_IFACE" | grep -q " ${BIND_IP}/"; then
    ip addr add "${BIND_IP}/32" dev "$BIND_IFACE"
  fi
}

ensure_chain() {
  iptables -t nat -N "$CHAIN" 2>/dev/null || iptables -t nat -F "$CHAIN"
  if ! iptables -t nat -C PREROUTING -j "$CHAIN" 2>/dev/null; then
    iptables -t nat -I PREROUTING 1 -j "$CHAIN"
  fi
  iptables -N "$FILTER_CHAIN" 2>/dev/null || iptables -F "$FILTER_CHAIN"
  if ! iptables -C INPUT -j "$FILTER_CHAIN" 2>/dev/null; then
    iptables -I INPUT 1 -j "$FILTER_CHAIN"
  fi
}

add_dnat() {
  local proto="$1"
  local dport="$2"
  local dest="$3"
  iptables -t nat -A "$CHAIN" -p "$proto" --dport "$dport" \
    -j DNAT --to-destination "$dest"
  iptables -A "$FILTER_CHAIN" -p "$proto" --dport "$dport" -j ACCEPT
}

apply_rules() {
  ensure_bind_iface
  ensure_chain
  if command -v ipset >/dev/null 2>&1; then
    ipset create "${EPHEMERAL_SET}" bitmap:port range 0-65535 -exist
    if ! ipset add "${EPHEMERAL_SET}" "${EPHEMERAL_PORT_MIN}-${EPHEMERAL_PORT_MAX}" -exist 2>/dev/null; then
      local p
      for p in $(seq "${EPHEMERAL_PORT_MIN}" "${EPHEMERAL_PORT_MAX}"); do
        ipset add "${EPHEMERAL_SET}" "$p" -exist
      done
    fi
  fi

  if [[ "$OVPN_UDP_ENABLED" == "1" ]]; then
    add_dnat udp "$OVPN_UDP_PORT" "${BIND_IP}:${OVPN_UDP_PORT}"
    if command -v ipset >/dev/null 2>&1; then
      iptables -t nat -A "$CHAIN" -p udp -m set --match-set "${EPHEMERAL_SET}" dst \
        -j DNAT --to-destination "${BIND_IP}:${OVPN_UDP_PORT}"
      iptables -A "$FILTER_CHAIN" -p udp -m set --match-set "${EPHEMERAL_SET}" dst -j ACCEPT
    fi
  fi
  if [[ "$OVPN_TCP_ENABLED" == "1" ]]; then
    add_dnat tcp "$OVPN_TCP_PORT" "${BIND_IP}:${OVPN_TCP_PORT}"
    if command -v ipset >/dev/null 2>&1; then
      iptables -t nat -A "$CHAIN" -p tcp -m set --match-set "${EPHEMERAL_SET}" dst \
        -j DNAT --to-destination "${BIND_IP}:${OVPN_TCP_PORT}"
      iptables -A "$FILTER_CHAIN" -p tcp -m set --match-set "${EPHEMERAL_SET}" dst -j ACCEPT
    fi
  fi
  if [[ "$WG_ENABLED" == "1" ]]; then
    add_dnat udp "$WG_PORT" "${BIND_IP}:${WG_PORT}"
  fi

  mkdir -p /etc/iptables
  if command -v ipset >/dev/null 2>&1; then
    ipset save > /etc/iptables/ipsets
  fi
  if command -v iptables-save >/dev/null 2>&1; then
    iptables-save > /etc/iptables/rules.v4
  fi
}

apply_rules
echo "popout-dnat: bind ${BIND_IP} udp=${OVPN_UDP_ENABLED}:${OVPN_UDP_PORT} tcp=${OVPN_TCP_ENABLED}:${OVPN_TCP_PORT} wg=${WG_ENABLED}:${WG_PORT}"
